{
  "openapi": "3.0.0",
  "info": {
<<<<<<< HEAD
    "description": "This is an API documentation for TiGrow LTD",
=======
    "description": "This is a simple API for TiGrow LTD",
>>>>>>> 834582bd... openapi.json added
    "version": "1.0.0-oas3",
    "title": "TiGrow LTD API",
    "contact": {
      "name": "API Support",
      "email": "alamariful1727@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
<<<<<<< HEAD
  
  "tags": [{
=======
  "tags": [
    {
<<<<<<< HEAD
>>>>>>> 834582bd... openapi.json added
      "name": "admins",
=======
      "name": "Admins",
>>>>>>> f52d2ce6... Documentation done for Category
      "description": "Secured Admin-only calls"
    },
    {
      "name": "Category : type",
      "description": "['job-seeker', 'emp', 'business', 'business-category']"
    }
  ],
<<<<<<< HEAD

  "paths": {
<<<<<<< HEAD
<<<<<<< HEAD
    "/account/signup": {
      "post": {
        "summary": "Create a new acount",
        "requestBody": {
          "description": "Optional description in *Markdown*",
=======
    "/category/{cid}": {
=======
    "/category": {
>>>>>>> f52d2ce6... Documentation done for Category
      "post": {
        "tags": ["Admins"],
        "summary": "Add a new category",
        "description": "",
        "operationId": "newCategory",
        "security": [{ "JWT": [] }],
        "requestBody": {
<<<<<<< HEAD
          "description": "name should be required and unique",
>>>>>>> 0cfa920d... Swagger added
=======
          "description": "name & type are required and name should be unique",
>>>>>>> f52d2ce6... Documentation done for Category
          "required": true,
          "content": {
            "application/json": {
              "schema": {
<<<<<<< HEAD
                "$ref": "#/components/schemas/Account"
=======
                "$ref": "#/components/schemas/NewCategory"
>>>>>>> 0cfa920d... Swagger added
              }
            }
          }
        },
        "responses": {
          "201": {
<<<<<<< HEAD
            "description": "Created"
          }
        }
      }
    },
    "/account/login": {
      "post": {
        "summary": "Login information about account",
        "requestBody": {
          "description": "Optional description in *Markdown*",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Account"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "loggedin"
          }
        }
      }
    },
    
      "/users/profile": {
        "get": {
          "description":"",
          "parameters": [],
          "responses": {
            "200": {
              "description":"Success"
            }
          }
        },
        "post": {
          "description":"Information about particular user",
          "security": [
            {
              "JWT": []
            }
          ],
          "requestBody": {
            "description": "Optional description in *Markdown*",
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegisteredUser"
=======
            "description": "`Created`",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "newCategory": {
                      "type": "object"
                    }
                  },
                  "example": {
                    "message": "Handling POST requests to /api/v1/category/new-category",
                    "newCategory": {
                      "__v": 0,
                      "name": "a",
                      "type": "job-seeker",
                      "_id": "5d076d2af1eae44eb46dbade",
                      "subcategories": []
                    }
                  }
>>>>>>> 0cfa920d... Swagger added
                }
              }
            }
          },
<<<<<<< HEAD
          "responses": {
            "200": {
              "description":"Success"
            },
            "401": {
              "description":"You don't have permissions for the resource"
            }
          }
        }
      },
      "/company/profile": {
        "post": {
          "description":"Send company info to the account",
          "security": [
            {
              "JWT": []
            }
          ],
          "requestBody": {
            "description": "value that would be pass",
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Company"
                }
              }
            }
          },
          "responses": {
            "200": {
              "description":"Success"
            },
            "401": {
              "description":"You don't have permissions for the resource"
            }
          }
        }
      },
    
    
    
=======
  "paths": {
>>>>>>> 834582bd... openapi.json added
=======
          "400": {
            "description": "Expects `name & type` in body"
          },
          "401": {
            "description": "`Unauthorized`"
          },
          "500": { "description": "`Internal Server Error`" }
        }
      },
      "get": {
        "tags": ["Category : type"],
        "summary": "Get category",
        "description": "By passing in the appropriate options, you can search for available category in the system.<br />  <h1>** `type: business && name: Category of one’s business`**<br /> Search: `/category?type=business-category` ",
        "parameters": [
          {
            "in": "query",
            "name": "type",
            "description": "pass category option",
            "required": true,
            "schema": {
              "type": "string",
              "enum": ["job-seeker", "emp", "business", "business-category"]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "type": {
                      "type": "string"
                    },
                    "categories": {
                      "type": "array"
                    }
                  },
                  "example": {
                    "type": "job-seeker",
                    "categories": [
                      {
                        "_id": "5cf367d2c8ec086b7c98a52f",
                        "name": "a"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Expects 'type' in query string"
          }
        }
      }
    },
<<<<<<< HEAD
>>>>>>> 0cfa920d... Swagger added
    "/category": {
=======
    "/category/{cid}": {
>>>>>>> f52d2ce6... Documentation done for Category
      "post": {
        "tags": ["Admins"],
        "summary": "Add a new sub-category",
        "description": "",
        "operationId": "newSubCategory",
        "security": [{ "JWT": [] }],
        "parameters": [
          {
            "name": "cid",
            "in": "path",
            "required": true,
            "description": "the category identifier, as cid",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "name should be required and unique",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewSubCategory"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "`Created`",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "newCategory": {
                      "type": "object"
                    }
                  },
                  "example": {
                    "message": "New sub-category created under Category: a",
                    "newSubCategory": {
                      "__v": 0,
                      "cid": {
                        "_id": "5d076d2af1eae44eb46dbade",
                        "name": "a",
                        "type": "job-seeker",
                        "__v": 1,
                        "subcategories": ["5d076d37f1eae44eb46dbadf"]
                      },
                      "name": "b",
                      "_id": "5d076d37f1eae44eb46dbadf",
                      "subsubcategories": []
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Expects `name` in body"
          },
          "401": {
            "description": "`Unauthorized`"
          },
          "500": { "description": "`Internal Server Error`" }
        }
      },
      "get": {
<<<<<<< HEAD
<<<<<<< HEAD
        "tags": ["front-end-developers"],
        "summary": "searches category",
        "operationId": "searchInventory",
        "description": "By passing in the appropriate options, you can search for\navailable category in the system\n",
<<<<<<< HEAD
        "parameters": [{
          "in": "query",
          "name": "type",
          "description": "pass category option",
          "required": true,
          "schema": {
            "type": "string",
            "enum": ["job-seeker", "emp", "business", "company"]
          }
        }],
=======
=======
        "tags": ["Category : Job-Seeker"],
        "summary": "Get category",
=======
        "tags": ["Category : type"],
        "summary": "Get sub-category",
>>>>>>> f52d2ce6... Documentation done for Category
        "description": "By passing in the appropriate options, you can search for available category in the system\n",
>>>>>>> 0cfa920d... Swagger added
        "parameters": [
          {
            "name": "cid",
            "in": "path",
            "required": true,
            "description": "the category identifier, as cid",
            "schema": {
              "type": "string"
            }
          }
        ],
>>>>>>> 834582bd... openapi.json added
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string",
                      "pattern": "^[0-9a-fA-F]{24}$"
                    },
                    "name": {
                      "type": "string"
                    },
                    "subcategories": {
                      "type": "array"
                    }
                  },
                  "example": {
                    "_id": "5d076d2af1eae44eb46dbade",
                    "name": "a",
                    "subcategories": [
                      {
                        "_id": "5d076d37f1eae44eb46dbadf",
                        "name": "b"
                      }
                    ]
                  }
                }
              }
            }
          },
          "500": { "description": "`Internal Server Error`" }
        }
      }
    },
    "/category/sub-category/{sid}": {
      "post": {
        "tags": ["Admins"],
        "summary": "Add a new sub-sub-category",
        "description": "",
        "operationId": "newSubSubCategory",
        "security": [{ "JWT": [] }],
        "parameters": [
          {
            "name": "sid",
            "in": "path",
            "required": true,
            "description": "the sub-category identifier, as sid",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "name should be required and unique",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewSubSubCategory"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "`Created`",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "newCategory": {
                      "type": "object"
                    }
                  },
                  "example": {
                    "message": "New sub-sub-category created under Sub-Category: b",
                    "newSubSubCategory": {
                      "__v": 0,
                      "sid": {
                        "_id": "5d076d37f1eae44eb46dbadf",
                        "cid": "5d076d2af1eae44eb46dbade",
                        "name": "b",
                        "__v": 1,
                        "subsubcategories": ["5d076d5af1eae44eb46dbae0"]
                      },
                      "cid": "5d076d2af1eae44eb46dbade",
                      "name": "c",
                      "_id": "5d076d5af1eae44eb46dbae0"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Expects `name` in body"
          },
          "401": {
            "description": "`Unauthorized`"
          },
          "500": { "description": "`Internal Server Error`" }
        }
      },
      "get": {
        "tags": ["Category : type"],
        "summary": "Get sub-sub-category",
        "description": "",
        "parameters": [
          {
            "name": "sid",
            "in": "path",
            "required": true,
            "description": "the sub-category identifier, as sid",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "_id": {
                      "type": "string",
                      "pattern": "^[0-9a-fA-F]{24}$"
                    },
                    "name": {
                      "type": "string"
                    },
                    "subsubcategories": {
                      "type": "array"
                    }
                  },
                  "example": {
                    "_id": "5d076d37f1eae44eb46dbadf",
                    "name": "b",
                    "subsubcategories": [
                      {
                        "_id": "5d076d5af1eae44eb46dbae0",
                        "name": "c"
                      }
                    ]
                  }
                }
              }
            }
          },
          "500": { "description": "`Internal Server Error`" }
        }
      }
    }
  },
<<<<<<< HEAD
  "servers": [{
    "url": "http://127.0.0.1:4040/api/v1",
    "description": "development server"
  }],
  "components": {
  
  "securitySchemes": {
      "JWT": {
          "type": "apiKey",
          "name": "Authorization",
          "in": "header"
      }
  },
    "schemas": {
      "Account":{
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "example": "o@o.com"
          },
          "password":{
            "type": "string",
            "example": "Rob@t124309"
          }
        }
      },
      "RegisteredUser":{
        "type": "object",
        "properties":{
          "name":{
            "type": "string",
            "example": "orvi das"
          },
          "gender":{
            "type":"string",
            "example":"m"
          },
          "skillArea": {
            "type": "string",
            "example": "node, react"
          },
          "mobileNumber":{
            "type": "string",
            "example": "8801683754716"
          },
          "secondaryEmail":{
            "type": "string",
            "example": "orvi1@gmail.com"
          },
          "birthday": {
            "type":"string",
            "example": "12/12/2018"
          },
          "about":{
            "type":"string",
            "example": "I love what I am doing."
          },
          "bio": {
            "type":"string",
            "example": "GOOD GOOD GOOD"
          }
        }
      },
      "Company":{
        "type": "object",
        "properties":{
          "companyName" :{
            "type" : "string",
            "example": "face@fb.com"
          },
          "phoneNumber" : {
            "type" : "string",
            "example" : "8801673754716"
          },
          "companyAddress" : {
            "type": "string",
            "example" : "mohkhali dohs"
          },
          "establishDate" : {
            "type" : "string",
            "example": "2019"
          },
          "selectDistrict":{
            "type" : "string",
            "example" : "Dhaka"
          },
          "selectThana" : {
            "type" : "string",
            "example" : "banani"
          },
          "businessDescription" : {
            "type" : "string",
            "example" : "Social network site"
          },
          "tradelicense":{
            "type": "string",
            "example" : "10000000"
          },
          "contactPersonName" : {
            "type" : "string",
            "example" : "orvi"
          },
          "contactPersonDesignation" : {
            "type" : "string",
            "example" : "software engineer"
          },
          "contactPersonemail": {
            "type": "string",
            "example" : "das.orvi@yahoo.com"
          },
          "contactPersonMobile": {
            "type": "string",
            "example" : "8801683754716"
          }
        }
      },
=======
  "servers": [
    {
      "url": "http://127.0.0.1:4040/api/v1"
    }
  ],
  "components": {
    "securitySchemes": {
      "JWT": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization"
      }
    },
    "schemas": {
<<<<<<< HEAD
>>>>>>> 834582bd... openapi.json added
=======
      "NewCategory": {
        "type": "object",
        "required": ["name", "type"],
        "properties": {
          "name": {
            "type": "string",
            "example": "a",
            "uniqueItems": true
          },
          "type": {
            "type": "string",
            "example": "job-seeker"
          }
        }
      },
<<<<<<< HEAD
>>>>>>> 0cfa920d... Swagger added
=======
      "NewSubCategory": {
        "type": "object",
        "required": ["name"],
        "properties": {
          "name": {
            "type": "string",
            "example": "b",
            "uniqueItems": true
          }
        }
      },
      "NewSubSubCategory": {
        "type": "object",
        "required": ["name"],
        "properties": {
          "name": {
            "type": "string",
            "example": "c",
            "uniqueItems": true
          }
        }
      },
>>>>>>> f52d2ce6... Documentation done for Category
      "Category": {
        "type": "object",
        "required": ["name", "type"],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[0-9a-fA-F]{24}$",
            "example": "5cf367d2c8ec086b7c98a52f"
          },
          "name": {
            "type": "string",
            "example": "Field of Expertise"
          },
          "type": {
            "type": "string",
            "enum": ["job-seeker", "emp", "business", "business-category"],
            "example": "job-seeker"
          },
          "subcategories": {
            "$ref": "#/components/schemas/SubCategory"
          }
        }
      },
      "SubCategory": {
        "required": ["cid", "name"],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[0-9a-fA-F]{24}$",
            "example": "5cf367d2c8ec086b7c98a52f"
          },
          "cid": {
            "$ref": "#/components/schemas/Category"
          },
          "name": {
            "type": "string",
            "example": "Engineering & Computer Science"
          },
          "subcategories": {
            "$ref": "#/components/schemas/SubSubCategory"
          }
        }
      },
      "SubSubCategory": {
        "required": ["cid", "sid", "name"],
        "properties": {
          "id": {
            "type": "string",
            "pattern": "^[0-9a-fA-F]{24}$",
            "example": "5cf367d2c8ec086b7c98a52f"
          },
          "cid": {
            "$ref": "#/components/schemas/Category"
          },
          "sid": {
            "$ref": "#/components/schemas/SubCategory"
          },
          "name": {
            "type": "string",
            "example": "Engineering & Computer Science"
          }
        }
      }
    }
  }
<<<<<<< HEAD
}
=======
}
>>>>>>> 834582bd... openapi.json added
